CREATE OR REPLACE TRIGGER actualizarNumActivos
AFTER INSERT ON ACTIVOS
FOR EACH ROW
DECLARE

BEGIN 
    UPDATE FUNCIONARIOS
    SET NUM_ACT_FUN = NUM_ACT_FUN + 1 
    WHERE ID_FUN = :NEW.ID_FUN_PER;
END
.
/